CREATE TABLE PUBLIC.box
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    dailyRate int NOT NULL,
    picURL varchar(45),
    size int NOT NULL,
    floor varchar(45) NOT NULL,
    window boolean  NOT NULL,
    outside boolean  NOT NULL,
    deleted boolean DEFAULT false NOT NULL
);
ALTER TABLE PUBLIC.box ADD CONSTRAINT unique_id UNIQUE (id);

CREATE TABLE PUBLIC.reservation
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    customerName varchar(45) NOT NULL,
    horseName varchar(45) NOT NULL,
    start date  NOT NULL,
    end date NOT NULL,
    check (start <= end),
    boxID int references box(id),
    receiptID int references receipt(id),
    dailyCharge int NOT NULL,
    payed boolean DEFAULT false NOT NULL
);
ALTER TABLE PUBLIC.reservation ADD CONSTRAINT unique_id UNIQUE (id);

CREATE TABLE PUBLIC.receipt
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    totalCharge int NOT NULL
);
ALTER TABLE PUBLIC.receipt ADD CONSTRAINT unique_id UNIQUE (id);
